### PR TITLE
Midproject

### PR DESCRIPTION
**Pull request by anjaliverma96**
Script that acquires data from data source and puts it into S3 is available in the src folder under downloaddata.py

To copy data from publicly accessible bucket "jokerecommender" to own private bucket, run:
python run.py loadS3 --bucket=
Script that creates database schema locally in sqlite is available in src folder under add_schema.py
2. To create the database in the location configured in config.py, run:
python run.py createSqlite

Script that creates database schema in RDS based on a configuration is available in src folder under add_schema.py
3. To create the database schema in AWS RDS, run:
python run.py createRDS

All variable declarations are in config.py

Add Schema-
https://github.com/anjaliverma96/Project/blob/master/src/add_schema.py
Download Data -
https://github.com/anjaliverma96/Project/blob/master/src/downloadData.py
Run -
https://github.com/anjaliverma96/Project/blob/master/run.py
Config -
https://github.com/anjaliverma96/Project/blob/master/config.py

### CODE REVIEW

**Comment by anjaliverma96** [comment]
> Please update requirements.txt to help install packages.

Could you let me know what part of the requirements.txt you had problems with so that I can update

**Comment by anjaliverma96** [comment]
> Getting the following error:
> botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
> 
> Do you know what could be the cause?

I will try updating my requirements.txt to see if the issue is fixed.

**Comment by sabarishchockalingam2017** [comment]
> > Please update requirements.txt to help install packages.
> 
> Could you let me know what part of the requirements.txt you had problems with so that I can update

I think the requirements.txt is blank, you can just do pip freeze > requirements.txt with your conda environment active to update it.

**Comment by sabarishchockalingam2017** [comment]
Functionality wise, the database initializing functions work well. I was able to create a local sqllite db file and was able to create the required tables in my rds instance.

I wasn't able to upload the files to my s3 bucket. This could be a fault on my side, my aws configurations may need to be updated. I will have to look into the botocore.exceptions.ClientError.

**Comment by sabarishchockalingam2017** [comment]
For Readability the code has been updated with comments and docstrings to explain decisions that were made and purpose of functions.

**Comment by sabarishchockalingam2017** [comment]
The code has good overall design. The code was already modularized into purposeful functions such as uploading to bucket and initializing databases. No update was needed in that regard.

**Comment by sabarishchockalingam2017** [comment]
Running the code is well documented in the readme. The files that required review were also clearly listed in the PR request. Commit statements are meaningful and addressed the comments I made to help improve the code.

**Comment by sabarishchockalingam2017** [comment]
The code is modularized so it is well structured to create tests. Tests have to be added at a later time as there aren't functions/code that is applicable for testing at this point.

**Pull request merged**
